name: '${project.name}'
authors: [ VoChiDanh ]
version: '${project.version}'
main: net.danh.backpacks.Backpacks
api-version: 1.14
commands:
  backpacks:
    description: BackPacks command
    aliases:
      - bp
      - backpack
      - bps
permissions:
  backpacks.getcommand:
    default: op
  backpacks.reload:
    default: op